name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump_by:
        description: "The version number to bump for the git tag"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch All Tags
        run: git fetch --force --tags
      - name: Determine Next Version
        id: next_version
        uses: zwaldowski/semver-release-action@v4
        with:
          dry_run: true
          bump: ${{ github.event.inputs.bump_by }}
          prefix: "v"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Tag Release
        run: |
          git config user.name "OpsLevel Bots"
          git config user.email "bots@opslevel.com"
          if [[ $(git diff --stat) != '' ]]; then
            git add .
            git commit -m "Cut Release '${{ steps.next_version.outputs.version_tag }}'"
            git push origin HEAD
          else
            echo "Skip commit"
          fi
          git tag -f ${{ steps.next_version.outputs.version_tag }} -m "Cut Release '${{ steps.next_version.outputs.version_tag }}'"
          git push -f origin refs/tags/${{ steps.next_version.outputs.version_tag }}
