
name: Cache Public Images

on:
  workflow_dispatch: {}

jobs:
  mysql:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/opslevel/platform-tools:v2022.11.19
    env:
      ECR_PRIVATE_REGISTRY: ${{ secrets.ECR_PRIVATE_REGISTRY }}
    steps:
      - name: Login to Private ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_PRIVATE_REGISTRY }}
          username: ${{ secrets.ECR_PRIVATE_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_PRIVATE_AWS_SECRET_ACCESS_KEY }}
      - name: Pull & Push
        run: |
          TAG=8.0.34-debian
          docker pull mysql:${TAG}
          docker tag mysql:${TAG} ${ECR_PRIVATE_REGISTRY}/mysql:${TAG}
          docker push ${ECR_PRIVATE_REGISTRY}/mysql:${TAG}
