
name: Cache Public Images

on:
  workflow_dispatch:
    inputs:
      mysql:
        required: true
        type: string

jobs:
  mysql:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/opslevel/platform-tools:v2022.11.19
    env:
      ECR_PRIVATE_REGISTRY: ${{ secrets.ECR_PRIVATE_REGISTRY }}
    steps:
      - name: Login to Private ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_PRIVATE_REGISTRY }}
          username: ${{ secrets.ECR_PRIVATE_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_PRIVATE_AWS_SECRET_ACCESS_KEY }}
      - name: Pull & Push
        run: |
          docker pull mysql:${{ inputs.mysql }} 
          docker tag mysql:${{ inputs.mysql }}  ${ECR_PRIVATE_REGISTRY}/mysql:${{ inputs.mysql }} 
          docker push ${ECR_PRIVATE_REGISTRY}/mysql:${{ inputs.mysql }} 
