
name: Cache Public Images

on:
  workflow_dispatch:
    inputs:
      source:
        required: true
        type: string
        default: "mysql"
      destination:
        required: true
        type: string
        default: "mysql"
      tag:
        required: true
        type: string
        default: "8.0.34-debian"

jobs:
  cache-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Private ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_PRIVATE_REGISTRY }}
          username: ${{ secrets.ECR_PRIVATE_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_PRIVATE_AWS_SECRET_ACCESS_KEY }}
      - name: Pull & Push
        run: |
          docker pull ${{ inputs.source }}:${{ inputs.tag }} 
          docker tag ${{ inputs.source }}:${{ inputs.tag }}  ${{ secrets.ECR_PRIVATE_REGISTRY }}/${{ inputs.destination }}:${{ inputs.tag }} 
          docker push ${{ secrets.ECR_PRIVATE_REGISTRY }}/${{ inputs.destination }}:${{ inputs.tag }} 
