name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup latest release of OpsLevel CLI
        uses: ./setup-cli/
      - name: run opslevel version
        run: opslevel version
      - name: setup specific version of OpsLevel CLI
        uses: ./setup-cli/
        with:
          cli_version: "v2024.10.28"
      # TODO: uncomment after the output is fixed
      # - name: run opslevel version
      #   run: opslevel version --short == "v2024.10.28"
